### ISSUE TITLE
Port is undefined

### ISSUE THREAD

**Issue by 72pitu** [SwagataChaudhuri/NestJS-AzureAD-Authentication#32]
Hi. Seems the config Service is not working. For me e.g. port is undefined when starting the service.

**Comment by SwagataChaudhuri** [comment]
Ideally we are supposed to create a .env file with a reference from the .env.example file and fill in the details there, by default the environment configuration is read from the .env file and hence there is no need to mention the envFilePath unless we need to separate out env file at per environment level, hope that helps and glad to see the issue is already resolved.

Marking this issues as closed hence !!
